### ISSUE TITLE
Napisać do Nordic TechComm

### ISSUE THREAD

**Issue by tomekprus** [techwriter-pl/techwriter-pl.github.io#29]

**Comment by tomekprus** [comment]
Andrzej planuje jechać, więc czemu nie napisać ws partnerstwa.

**Comment by andrzejniewiaro** [comment]
Chodzi o te konfe: 

TechKomm Stockholm March 06-07, 2024

Od stycznia zreszta wstapimy do tego Tekom Association.

**Comment by andrzejniewiaro** [comment]
Polechalem ;)
